[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
via_ir = true
solc_version = '0.8.16'
gas_reports = ["NFTMarketplaceRouter", "ReferenceNFTMarketplaceRouter"]

[fmt]
line_length = 120
quote_style = 'single'

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
